export const SERVER_PORT = 'SERVER_PORT';

export const DB_HOST='DB_HOST'
export const DB_PORT='DB_PORT'
export const DB_DATABASE='DB_DATABASE'
export const DB_USER='DB_USER'
export const DB_PASSWORD='DB_PASSWORD'

export const JWT_SECRET = 'JWT_SECRET'
export const JWT_RECOVERY_SECRET = 'JWT_RECOVERY_SECRET'
export const EXPIRES_IN = 'EXPIRES_IN'
export const EXPIRES_TEMPORAL_IN = 'EXPIRES_TEMPORAL_IN'

export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME'
export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY'
export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET'

export const MAIL_HOST = 'MAIL_HOST'
export const MAIL_PORT = 'MAIL_PORT'
export const MAIL_USER = 'MAIL_USER'
export const MAIL_PASSWORD = 'MAIL_PASSWORD'
export const FRONTEND_URL = 'FRONTEND_URL'
export const EXPIRES_CODE = 'EXPIRES_CODE'
export const FASTAPI_URL = 'FASTAPI_URL'